### ISSUE TITLE
cant set http headers user agent

### ISSUE THREAD

**Issue by TSCSOftware** [jakky1/video_player_control_panel#1]
i m trying to set user agent but it always 'NSPlayer/12.00.19041.2604 WMFSDK/12.00.19041.2604'
    controller = VideoPlayerController.network('$urls', httpHeaders: {
      'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0',
      'Accept':
          'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.5',
      'Accept-Encoding': 'gzip, deflate',
      'Connection': 'keep-alive',
      
    });

**Comment by jakky1** [comment]
Assumes your app is running on Windows.

After the survey,
Windows Media Foundation API only support assign some limited headers : user-agent & Referer
_( keyword: IMFSourceResolver::BeginCreateObjectFromURL , IPropertyStore  , [MFNETSOURCE_](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/medfound/mfnetsource-enable-http-property.md)** )_

So, is it acceptable to you if ONLY the [user-agent] header works ?
If yes, I will try to fix it.
If no, this issue will be [wontfix]

**Comment by jakky1** [comment]
Unfortunately,
after an hour of try, it seems that microsoft media foundation ignores the related settings.
so this issue wont fix :(

**Comment by TSCSOftware** [comment]
IMFMediaSource* pSource = NULL;
IMFSourceResolver* pSourceResolver = NULL;
HRESULT hr = MFCreateSourceResolver(&pSourceResolver);
if (FAILED(hr))
{
    // Handle error
}

// Create a property store to hold the HTTP headers
IPropertyStore* pPropertyStore = NULL;
hr = MFCreatePropertyStore(&pPropertyStore);
if (FAILED(hr))
{
    // Handle error
}

// Set the custom HTTP headers
PROPVARIANT var;
PropVariantInit(&var);
var.vt = VT_BSTR;
var.bstrVal = SysAllocString(L"Authorization: Bearer TOKEN");
hr = pPropertyStore->SetValue(MF_HTTP_REQUEST_HEADERS, var);
if (FAILED(hr))
{
    // Handle error
}

// Create a property store to hold the URL
PROPVARIANT varURL;
PropVariantInit(&varURL);
varURL.vt = VT_BSTR;
varURL.bstrVal = SysAllocString(L"http://example.com/video.mp4");

// Create the media source
MF_OBJECT_TYPE ObjectType = MF_OBJECT_INVALID;
hr = pSourceResolver->CreateObjectFromURL(varURL.bstrVal, MF_RESOLUTION_MEDIASOURCE, pPropertyStore, &ObjectType, (IUnknown**)&pSource);
if (FAILED(hr))
{
    // Handle error
}

// Cleanup
PropVariantClear(&var);
PropVariantClear(&varURL);
SafeRelease(&pSourceResolver);
SafeRelease(&pPropertyStore);

**Comment by TSCSOftware** [comment]
#include "windows_media_player.h"

#include <string>
#include <codecvt>
#include <iostream>

#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Media.Core.h>
#include <winrt/Windows.Media.Playback.h>
#include <winrt/Windows.Storage.h>
#include <winrt/Windows.Web.Http.Headers.h>

namespace {

std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;

}

WindowsMediaPlayer::WindowsMediaPlayer() = default;

WindowsMediaPlayer::~WindowsMediaPlayer() = default;

void WindowsMediaPlayer::CreateMediaSource(
    const std::string& uri, const std::map<std::string, std::string>& headers, winrt::Windows::Media::Core::MediaSource& media_source) const {
  auto w_uri = converter.from_bytes(uri);
  auto uri_obj = winrt::Windows::Foundation::Uri(w_uri);

  winrt::Windows::Web::Http::Headers::HttpRequestHeaderCollection header_collection;
  for (const auto& [key, value] : headers) {
    auto w_key = converter.from_bytes(key);
    auto w_value = converter.from_bytes(value);
    header_collection.TryAppendWithoutValidation(w_key, w_value);
  }

  winrt::Windows::Web::Http::HttpClient client;
  client.DefaultRequestHeaders().InsertRange(header_collection);

  auto response = client.GetAsync(uri_obj).get();
  response.EnsureSuccessStatusCode();

  auto stream = response.Content().ReadAsInputStreamAsync().get();

  auto content_type = response.Content().Headers().ContentType().MediaType();

  auto content_type_w = converter.from_bytes(content_type);
  auto media_stream_type = winrt::Windows::Media::Core::MediaStreamType::FromMediaType(content_type_w);

  auto media_stream_source = winrt::Windows::Media::Core::MediaStreamSource::CreateFromInputStream(stream);
  media_stream_source.AddMediaStream(media_stream_type, stream);
  media_source = winrt::Windows::Media::Core::MediaSource(media_stream_source);
}

void WindowsMediaPlayer::Play(const std::string& uri, const std::map<std::string, std::string>& headers) const {
  winrt::Windows::Media::Core::MediaSource media_source;
  CreateMediaSource(uri, headers, media_source);

  winrt::Windows::Media::Playback::MediaPlayer player;
  player.Source(media_source);
  player.Play();
}

**Comment by jakky1** [comment]
The sample code you provided create a HttpClient and send request itself.
It is not meaningful if not ask media foundation player to do http request.
BTW, please don't use ChatGPT without validation.
